export const ErrorCode = {
  // 공통
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  // 인증
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  // 권한
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  FORBIDDEN_RESOURCE: 'FORBIDDEN_RESOURCE',
  // 카페 / 할인
  CAFE_NOT_FOUND: 'CAFE_NOT_FOUND',
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  DISCOUNT_INVALID_PERIOD: 'DISCOUNT_INVALID_PERIOD',
  // 결제수단
  PAYMENT_METHOD_NOT_FOUND: 'PAYMENT_METHOD_NOT_FOUND',
  // 제보
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_SELF_CONFIRM: 'REPORT_SELF_CONFIRM',
  REPORT_CONFIRM_CLOSED: 'REPORT_CONFIRM_CLOSED',
  REPORT_ALREADY_REGISTERED: 'REPORT_ALREADY_REGISTERED',
  REPORT_REVIEW_CLOSED: 'REPORT_REVIEW_CLOSED',
  // 즐겨찾기 / 알림
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  PAYMENT_ALERT_NOT_FOUND: 'PAYMENT_ALERT_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  // 디바이스
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  // 크롤 후보 검수
  CRAWL_CANDIDATE_NOT_FOUND: 'CRAWL_CANDIDATE_NOT_FOUND',
  CRAWL_CANDIDATE_REVIEW_CLOSED: 'CRAWL_CANDIDATE_REVIEW_CLOSED',
  CRAWL_CANDIDATE_NO_CAFE: 'CRAWL_CANDIDATE_NO_CAFE',
  CRAWL_CANDIDATE_INVALID_PARSED: 'CRAWL_CANDIDATE_INVALID_PARSED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
